model_type: "SimCLR"
lr_warmup_epochs: 10
lr_mult: 1
epoch: 0
n_epoch: 200
log_freq: 10
checkpoint_freq: 5
# phase: "pretraining"
exp_name: 'SimCLR_kaggle_oct_multiple'
architecture: 'simclr'
wandb:
  project: 'Eye2Gene'
  username: 'pstha'
model:
  augmented_generating_model: "MAE"
  augmented_pretrained_path: "/raid/binod/prashant/eye2gene/logs/MAE_kaggle_oct_single/models/best.pth"
  pass_through_separately: False
  temperature: 0.5
  pretrained_params:
    img_sz: 224
    patch_sz: 16
    in_chans: 3
    emb_dim: 384
    dec_emb_dim: 512
    depth : 12
    dec_depth : 2
    num_heads : 6
    dec_num_heads : 16
    mlp_ratio : 4
    mask_ratio : 0.90

  image:
    proj_dim: 384

data:
  dataset: "kaggle_oct_multiple"
  split_ratio: 0.8
  batch_size : 1
  num_workers: 8
  train:
    im_size: 224
    transform_type: "train"
    per_patient_images: 16
    root_dir: "/raid/binod/prashant/eye2gene/OCT-patientwise/train"
  val:
    im_size: 224
    transform_type: "val"
    per_patient_images: 10
    root_dir: "/raid/binod/prashant/eye2gene/OCT-patientwise/val"
  test:
    im_size: 224
    transform_type: "test"
    per_patient_images: 10
    root_dir: "/raid/binod/prashant/eye2gene/OCT-patientwise/test"
optimizer:
  name: "AdamW"
  weight_decay: 0.05
  lr : 1.0e-5
